spring:
  application:
    name: customer-service
  config:
    import: "optional:configserver:http://localhost:8888"
logging:
  file:
    name: ./build/logs/customerServiceApplication.log
  level:
    org.springframework.boot.web.embedded.netty: info
