spring:
  application:
    name: customer-service
  config:
    import: "optional:configserver:http://localhost:8888"
  boot:
    admin:
      client:
        url: "http://localhost:8090/admin"
#        instance:
#          service-host-type: ip
logging:
  file:
    name: ./build/logs/customerServiceApplication.log
  level:
    org.springframework.boot.web.embedded.netty: info

management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: "*"
