party-webMvc:
  yaml:
server:
  port: 8084
  shutdown: graceful

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0

spring:
  threads:
    virtual:
      enabled: true