version: "3.9"

services:
  service-registry:
    restart: on-failure
    build:
      context: ./
      dockerfile: ./service-registry/Dockerfile
    container_name: ${PROJECT_NAME:-default}-service-registry-prod-container
    ports:
      - 8761
    environment:
      PORT: 8761

  config-server:
    restart: on-failure
    build:
      context: ./
      dockerfile: ./config-server/Dockerfile
    container_name: ${PROJECT_NAME:-default}-config-server-prod-container
    ports:
      - 8888
    environment:
      PORT: 8888
    depends_on:
      - service-registry

  api-gateway:
    build:
      context: ./
      dockerfile: ./api-gateway/Dockerfile
    container_name: ${PROJECT_NAME:-default}-api-gateway-prod-container
    ports:
      - 80:8080
    depends_on:
      - config-server
      #      - manufacturing-or-procurement-service
      # - book-service
      # - comment-service