version: "3.1"
services:

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus-config/:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    ports:
      - 9090:9090
    restart: always

  blackbox-exporter:
    image: prom/blackbox-exporter
    ports:
      - 9115:9115

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/

  prometheus-demo-app:
    image: backend/address-webMvc
    ports:
      - 8080:8080
    environment:
      - EUREKA_SERVICE_URI=http://srvice-registory:8761/eureka
    depends_on:
      - config-server
    restart: always

  config-server:
    image: backend/config-server
    ports:
      - 8761:8761
    environment:
      - EUREKA_SERVICE_URI=http://srvice-registory:8761/eureka
    depends_on:
      - srvice-registory
    restart: always

  srvice-registory:
    image: backend/srvice-registory
    ports:
      - 8761:8761