spring:
  application:
    name: address-service
  config:
    import: "optional:configserver:http://localhost:8888"
  r2dbc:
    url: "r2dbc:postgres://localhost:5432/projectName"
    username: user
    password: password
  threads:
    virtual:
      enabled: true
  lifecycle:
    timeout-per-shutdown-phase: 15s
  flyway:
    url: jdbc:postgresql://localhost:5432/projectName
    driver-class-name: org.postgresql.Driver
    create-schemas: true
    out-of-order: true

  main:
    web-application-type: reactive

logging:
  file:
    name: ./build/logs/addressServiceApplication.log
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"


