spring:
  application:
    name: manufacturing-or-procurement-service
  config:
    import: "optional:configserver:http://localhost:8888"
  r2dbc:
    url: "r2dbc:postgres://localhost:5432/projectName"
    username: user
    password: password

logging:
  file:
    name: ./build/logs/manufacturingOrProcurementServiceApplication.log
  #  level:
  #    web: WARN
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

