spring:
  application:
    name: employee-service
  config:
    import: "optional:configserver:http://localhost:8888"
logging:
  file:
    name: ./build/logs/employeeServiceApplication.log
  level:
    web: warn

management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: "*"
