spring:
  application:
    name: address-service
  config:
    import: "optional:configserver:http://localhost:8888"
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/projectName
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-test-query: SELECT 1
      connection-timeout: 60000                  # Default: 30000 (30 seconds)
      minimum-idle: 2                           # Default: same as maximumPoolSize
      maximum-pool-size: 10
      schema: address
  jpa:
    database: postgresql
    #    hibernate:
    #      ddl-auto: update
    show-sql: true

  flyway:
    url: jdbc:postgresql://localhost:5432/projectName
    driver-class-name: org.postgresql.Driver
    create-schemas: true
    out-of-order: true
  lifecycle:
    timeout-per-shutdown-phase: 15s
  threads:
    virtual:
      enabled: true

  main:
    web-application-type: SERVLET

logging:
  file:
    name: ./build/logs/addressServiceApplication.log
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    root: info


