spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8888"
  boot:
    admin:
      client:
        url: http://localhost:8090/admin
  cloud:
    gateway:
      routes:
        - id: ADDRESS-SERVICE
          uri: http://localhost:8085
          predicates:
            - Path=/api/*/prefectures/**,/api/*/cities/**
logging:
  file:
    name: ./build/logs/ApiGatewayApplication.log

management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: "*"


