spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8888"
  boot:
    admin:
      client:
        url: http://localhost:8090/admin
  cloud:
    gateway:
      routes:
        - id: DEPARTMENT-SERVICE
          uri: http://localhost:8081
          predicates:
            - Path=/api/{apiVersion}/departments/**
        - id: ADDRESS-SERVICE
          uri: http://localhost:8085
          predicates:
            - Path=/api/{apiVersion}/prefectures/**,/api/{apiVersion}/municipals/**
      httpclient:
        pool:
          max-idle-time: 55s
logging:
  file:
    name: ./build/logs/ApiGatewayApplication.log
  level:
    web: WARN

management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: "*"


