spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8888"
  cloud:
    gateway:
      routes:
        - id: department-service
          uri: lb://department-service
          predicates:
            - Path=/api/{apiVersion}/departments/**
        - id: address-service
          uri: lb://address-service
          predicates:
            - Path=/api/{apiVersion}/prefectures/**,/api/{apiVersion}/municipals/**
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/api/{apiVersion}/employees/**
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/{apiVersion}/inventories/**
        - id: relationship-service
          uri: lb://relationship-service
          predicates:
            - Path=/api/{apiVersion}/people/**,/api/{apiVersion}/customers/**
      httpclient:
        pool:
          max-idle-time: 55s
  threads:
    virtual:
      enabled: true

logging:
  file:
    name: ./build/logs/ApiGatewayApplication.log
#  level:
#    web: WARN
#    root: warn


