spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8888"
  cloud:
    gateway:
      routes:
        - id: admin-server
          uri: lb://admin-server
          predicates:
            - Path=/admin/**
        - id: address-service
          uri: lb://address-service
          predicates:
            - Path=/address/api/{apiVersion}/**
          filters:
            - RewritePath=/address/?(?<segment>.*), /$\{segment}
        - id: relationship-service
          uri: lb://relationship-service
          predicates:
            - Path=/party/api/{apiVersion}/**,/party-role/api/{apiVersion}/**,/person-role/api/{apiVersion}/**,/organization-role/api/{apiVersion}/**
        - id: adjustment-and-support-service
          uri: lb://adjustment-and-support-service
          predicates:
            - Path=/account/api/{apiVersion}/**,/project/api/{apiVersion}/**,/document/api/{apiVersion}/**
        - id: sale-service
          uri: lb://sake-service
          predicates:
            - Path=/cash-sales/api/{apiVersion}/**
        - id: manufacturing-or-procurement-service
          uri: lb://manufacturing-or-procurement-service
          predicates:
            - Path=/manu-process/api/{apiVersion}/**,/material-resources/api/{apiVersion}/**,/inventory/api/{apiVersion}/**
        - id: all-in-one-service
          uri: lb://all-in-one-service
          predicates:
            - Path=/all-in-one/api/{apiVersion}/**
      httpclient:
        pool:
          max-idle-time: 55s
  threads:
    virtual:
      enabled: true

logging:
  file:
    name: ./build/logs/ApiGatewayApplication.log
  level:
    #    web: WARN
    root: warn


