spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8888"
  cloud:
    gateway:
      routes:
        - id: address-service
          uri: lb://address-service
          predicates:
            - Path=/api/{apiVersion}/address/**
        - id: relationship-service
          uri: lb://relationship-service
          predicates:
            - Path=/api/{apiVersion}/party/**,/api/{apiVersion}/party-role/**,/api/{apiVersion}/person-role/**,/api/{apiVersion}/organization-role/**
        - id: adjustment-and-support-service
          uri: lb://adjustment-and-support-service
          predicates:
            - Path=/api/{apiVersion}/projects/**
        - id: sale-service
          uri: lb://sake-service
          predicates:
            - Path=/api/{apiVersion}/cash-sales/**
        - id: manufacturing-or-procurement-service
          uri: lb://manufacturing-or-procurement-service
          predicates:
            - Path=/api/{apiVersion}/manu-process/**,/api/{apiVersion}/material-resources/**,/api/{apiVersion}/inventory/**
      httpclient:
        pool:
          max-idle-time: 55s
  threads:
    virtual:
      enabled: true

logging:
  file:
    name: ./build/logs/ApiGatewayApplication.log
#  level:
#    web: WARN
#    root: warn


