server:
  port: 8090
  servlet:
    context-path: /admin

spring:
  application:
    name: admin-server # アプリケーション名
  boot:
    admin:
      server:
        monitor:
          status-interval: 30000
      client:
        url: http://localhost:8090/admin
  thymeleaf:
    check-template-location: false

  config:
    import: "optional:configserver:http://localhost:8888"
logging:
  file:
    name: ./build/logs/adminServerApplication.log

management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: "*"
  security:
    enabled: false