spring:
  application:
    name: product-sale-service
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/kotlin_db
    username: user
    password: password
  jpa:
    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
    hibernate:
      ddl-auto:
  r2dbc:
    url: r2dbc:postgres://localhost:5432/kotlin_db
    username: user
    password: password

  config:
    import: "optional:configserver:http://localhost:8888"

logging:
  file:
    name: ./build/logs/productSaleServiceApplication.log
  #  level:
  #    web: WARN
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

