spring:
  application:
    name: product-sale-service
  config:
    import: "optional:configserver:http://localhost:8888"

logging:
  file:
    name: ./build/logs/productSaleServiceApplication.log
  level:
    web: WARN

