server:
  port: 8888

spring:
  application:
    name: config-server
  threads:
    virtual:
      enabled: true
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: "classpath:/config/"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  file:
    name: ./build/logs/configServerApplication.log
#  level:
#    web: WARN
#    root: warn



