spring:
  application:
    name: sale-service
  config:
    import: "optional:configserver:http://localhost:8888"
  r2dbc:
    url: "r2dbc:postgres://localhost:5432/projectName"
    username: user
    password: password
    pool:
      max-size: 10
      initial-size: 2
  flyway:
    url: jdbc:postgresql://localhost:5432/projectName
    driver-class-name: org.postgresql.Driver
    create-schemas: true
    out-of-order: true
  lifecycle:
    timeout-per-shutdown-phase: 15s
  threads:
    virtual:
      enabled: true

logging:
  file:
    name: ./build/logs/SaleServiceApplication.log
  level:
    web: info

