spring:
  application:
    name: sale-service
  config:
    import: "optional:configserver:http://localhost:8888"

logging:
  file:
    name: ./build/logs/SaleServiceApplication.log
  level:
    web: info

