spring:
  application:
    name: address-service
  config:
    import: "optional:configserver:http://localhost:8888"
  r2dbc:
    url: "r2dbc:postgres://localhost:5432/kotlin_db"
    username: user
    password: password
  flyway:
    url: "jdbc:postgresql:localhost:5432/kotlin_db"
    locations: "classpath:db/migration"
    driver-class-name: org.postgresql.Driver
  threads:
    virtual:
      enabled: true
logging:
  file:
    name: ./build/logs/addressServiceApplication.log
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"


