spring:
  application:
    name: adjustment-and-support-service
  config:
    import: "optional:configserver:http://localhost:8888"
  r2dbc:
    url: "r2dbc:postgres://localhost:5432/projectName"
    username: user
    password: password
    pool:
      max-size: 10
      initial-size: 2
  lifecycle:
    timeout-per-shutdown-phase: 15s
  flyway:
    url: jdbc:postgresql://localhost:5432/projectName
    driver-class-name: org.postgresql.Driver
    create-schemas: true
    out-of-order: true

  main:
    web-application-type: reactive
server:
  shutdown: graceful
logging:
  file:
    name: ./build/logs/adjustmentAndSupportServiceApplication.log
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"


